### ISSUE TITLE
Support for the latest msbuild version (16)

### ISSUE THREAD

**Issue by VladislavAntonyuk** [cake-contrib/Cake.MSBuildTask#7]
MSBuild
The MSBuild toolset version has been changed from 15.0 to Current. MSBuild.exe is now in %VSINSTALLDIR%\MSBuild\Current\Bin\MSBuild.exe.
MSBuild (and Visual Studio) now targets .NET Framework 4.7.2. If you wish to use new MSBuild API features, your assembly must also upgrade, but existing code will continue to work.

**Comment by gep13** [comment]
@VladislavAntonyuk sorry that no-one has replied to you before now.

I have just updated the addin here to use the latest version of Cake, and to target .Net 4.6.1 (which is the base version that Cake is provided for).

Can you provide a set of steps to reproduce the problem that you are facing?  Or, if you are in position to do so, can you provide a PR to provide the functionality that you require?
